### ISSUE TITLE
Feature: Create Banner

### ISSUE THREAD

**Issue by Safnaj** [GitHubExperts-LK/openhackday-lk#12]
![Screenshot 2021-10-15 at 1 33 30 PM](https://user-images.githubusercontent.com/37530024/137453407-18152d9c-a939-4adc-88fa-e722c398a32c.png)

Create a Banner Component as shown in the image.
path : components/Banner/Banner.tsx

**Comment by shanjathurshan** [comment]
Can you assign this to me ? I started working on this!

**Comment by Shehanka** [comment]
> Can you assign this to me ? I started working on this!

done

**Comment by Safnaj** [comment]
> Can you assign this to me ? I started working on this!

I've done this with Eslint rule change. Will create new issue in a while
