### ISSUE TITLE
Feature: Create Navbar

### ISSUE THREAD

**Issue by Safnaj** [GitHubExperts-LK/openhackday-lk#7]
Refer the below UI :
![Screenshot 2021-10-12 at 12 55 53 AM](https://user-images.githubusercontent.com/37530024/136845348-d371a9a9-b684-49b9-ac46-10872c87753c.png)
 
Figma URL : https://www.figma.com/file/Mb4bdGZaHeSZlswyk5bwY2/OpenHackDayLK?node-id=0%3A1

**Comment by MadhushaPrasad** [comment]
@Safnaj in progress this issue in my local repo. Can I assign this also

**Comment by Shehanka** [comment]
> @Safnaj Can you assign this to me?

@shanjathurshan Currently a PR #13 is open for this so can you pick #11 or #12

**Comment by shanjathurshan** [comment]
@Shehanka  yeah I finished #11 and #12 also create a pull request too. can you please check!

**Comment by Shehanka** [comment]
> @Shehanka yeah I finished #11 and #12 also create a pull request too. can you please check!

Where's the PR?
